### ISSUE TITLE
Einheitliche Initialisierung

### ISSUE THREAD

**Issue by marbetschar** [Mandelkind/ActivityIndicatorView#10]
Geht in die gleiche Richtung wie #9:

Du hast aktuell einige Properties die Du gleich im Klassenkopf initialisierst - im Gegensatz um textLabel, was Du im Konstruktor initialisierst.

Auch hier ist es mir Grundsätzlich egal, wie Du es machen möchtest - nur bitte einheitlich ;)

**Comment by florianthompson** [comment]
Habe mich für den Klassenkopf entschieden. ;)
