### ISSUE TITLE
Konstruktor: fatalError vermeiden

### ISSUE THREAD

**Issue by marbetschar** [Mandelkind/ActivityIndicatorView#11]
Wie kannst Du den folgenden fatalError vermeiden, ohne das Du gleich eine komplexe Methode implementieren musst?

```
required init?(coder aDecoder: NSCoder) {
   fatalError("init(coder:) has not been implemented")
}
```

**Comment by florianthompson** [comment]
Indem ich die Initialisierung des TextLabels im Klassenkopf erledige? Somit spare ich mir die Init-Methode zu überschreiben.

**Comment by marbetschar** [comment]
Elegant umschifft ;)

Alternativ habe ich folgenden Vorschlag (wenn Du's mal nicht umschiffen kannst):

```
required init?(coder aDecoder: NSCoder) {
  super.init(coder: aDecoder)
}
```

**Comment by florianthompson** [comment]
Super! 
Merci
