### ISSUE TITLE
Getter & Setter: Erwartungshaltung

### ISSUE THREAD

**Issue by marbetschar** [Mandelkind/ActivityIndicatorView#2]
Bei Setter Funktionen ist meine Erwartungshaltung, dass ich diesen einen Wert übergeben kann, der gesetzt wird (siehe: http://panjutorials.de/java-tutorial-19-setter-getter/). Das ist bei den Funktionen `setBackgroundView()`, `setLoadingView()`etc. nicht der Fall.

Was ist die Idee dieser Funktionen? Braucht es die überhaupt als Funktionen? Falls ja, wofür sind diese Zuständig (die Idee dahinter - nicht was der Code macht)?

**Comment by florianthompson** [comment]
Ich habe die Funktionen umbenannt zu "createContainerView" bzw. "createLoadingView". 
Der Gedanke hintern den Funktionen war das erhoffte einfachere Lesen. 

Jetzt wo ich von "lazy" erfahren habe, wäre das auch eine Option? 

lazy var loadingView = { ... } ? (Frage und kein Optional) ;)

**Comment by florianthompson** [comment]
Habe soeben erkannt, dass lazy und computed nicht funktioniert. 
Dann ändere ich meinen Vorschlag zu computed properties anstelle der Funktionen.

**Comment by marbetschar** [comment]
Warum funktionieren `lazy` properties nicht...?

**Comment by florianthompson** [comment]
Nehme es zurück. Der Compiler meinte lazy funktioniert nicht bei computed properties, aber habe es gelöst. ;-)
Funktioniert doch!
