### ISSUE TITLE
Lazy Initialization with Swift

### ISSUE THREAD

**Issue by marbetschar** [Mandelkind/ActivityIndicatorView#8]
Sehr lesenswert: http://mikebuss.com/2014/06/22/lazy-initialization-swift/
Bitte auf die bestehenden Properties anwenden wo sinnvoll.

**Comment by florianthompson** [comment]
Ein Traum! Vielen Dank!
Meines Erachtens betrifft das in erster Linie das TextLabel. 
Oder findest du es geschickter alle properties als lazy zu deklarieren, nachdem sie ja erst nach dem hinzufügen als SubView initialisiert werden müssten?

**Comment by marbetschar** [comment]
`lazy` Properties sind für mich auch noch neu - sehe allerdings keinen Grund, diese im aktuellen Fall nicht für alle Properties anzuwenden.

Live und in Farbe kannst Du diese auch im Eureka Projekt abgucken:
https://github.com/xmartlabs/Eureka/blob/master/Source/Cells.swift
